### ISSUE TITLE
Create horizontal bar chart

### ISSUE THREAD

**Issue by midhun-murali** [hadiidbouk/ChartProgressBar-Android#1]
Is there any way I can create a horizontal bar chart using this library

**Comment by hadiidbouk** [comment]
I thought of doing that recently but i didn't have time for it.
Also i haven't found the ideal design for the horizontal chart.
I will appreciate if you send me a PR  :)
or just wait till this feature to be added .

Thank you

**Comment by midhun-murali** [comment]
Thanks for the instant response, you can use almost the same design as of currently used in vertical bar charts. It would look awesome. If you have time, please add the feature soon. This is one of the most beautiful designs I have seen on bar charts.
