### ISSUE TITLE
Resources$NotFoundException: Resource ID #0x0 on androidx

### ISSUE THREAD

**Issue by ghost** [hadiidbouk/ChartProgressBar-Android#7]
Lib not working with androidx

**Comment by ghost** [comment]
My bug, sorry .)

**Comment by guyhatzav** [comment]
Hi :) I have the same problem, how did you fix that? Thx in advance :)

**Comment by guyhatzav** [comment]
> Hi :) I have the same problem, how did you fix that? Thx in advance :)

Ok I fixed it as well, the bug happend because I forgot to add the file ic_pin.xml from the sample folder.
