### ISSUE TITLE
Cannot resolve symbol '@drawable/ic_pin

### ISSUE THREAD

**Issue by Halimeh-manaf** [hadiidbouk/ChartProgressBar-Android#8]
Has anyone faced this problem? 

I tried to google it and search but nothing came out. 

Any ideas?

**Comment by hadiidbouk** [comment]
Hello Halimeh,

It seems that the icon pin named "ic_pin" is missing from your drawable folder, try to add it and It should work

**Comment by Halimeh-manaf** [comment]
Thank you for your reply. I added it successfully. Worked smoothly!
